name: Build and push image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/miniflux-exporter *.go

      - name: List files in ./bin directory
        run: |
          ls -lhr ./bin
      
      - uses: actions/upload-artifact@master
        with:
          name: compiled-binary
          path: ./bin/miniflux-exporter

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build-binary
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@master
        with:
          name: compiled-binary
          path: ./bin/miniflux-exporter

      - name: List files in ./bin directory
        run: |
          ls -lhr ./bin

      - name: List files in current directory
        run: |
          pwd
          ls -lhr .

      - name: Login to Docker Hub
        uses: docker/login-action@latest
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: rogierlommers/miniflux-exporter:latest
